<script setup>
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import PrivacyNotice from '../components/PrivacyNotice.vue'
import SiteNav from '../components/SiteNav.vue'
import SiteFooter from '../components/SiteFooter.vue'
import RadioSubnav from '../components/RadioSubnav.vue'
import { api } from '../lib/api'

const { locale } = useI18n()
const templates=ref([]), inbox=ref([]), outbox=ref([]), error=ref(''), notice=ref(''), busy=ref(''), tab=ref('inbox')
const upload=ref({name:'',dataUrl:'',preview:'',fileName:''})
const copy=computed(()=>({
 zh:{kicker:'// ELECTRONIC QSL',title:'QSL 中心',intro:'上传自己的 QSL 设计作为底图。通联信息不会永久写入原图，而是在发送和展示时动态叠加。',templates:'我的 QSL 模板',upload:'上传新 QSL',name:'模板名称',pick:'选择图片',hint:'PNG / JPEG / WebP，最大 5 MB。推荐 3:2，例如 1500×1000。',save:'保存模板',default:'默认',setDefault:'设为默认',remove:'删除',inbox:'收件箱',outbox:'已发送',emptyInbox:'还没有收到电子 QSL。',emptyOutbox:'还没有发送电子 QSL。',received:'确认收到',receivedDone:'已收到',from:'FROM',to:'TO',date:'DATE',time:'TIME',freq:'FREQ',mode:'MODE',rst:'RST',uploadOk:'QSL 模板已上传。',receivedOk:'已确认收到该 QSL。'},
 en:{kicker:'// ELECTRONIC QSL',title:'QSL Center',intro:'Upload your own QSL artwork as a base image. QSO data is kept separate and overlaid dynamically when the card is sent or displayed.',templates:'MY QSL TEMPLATES',upload:'UPLOAD QSL',name:'Template name',pick:'Choose image',hint:'PNG / JPEG / WebP, up to 5 MB. Recommended ratio 3:2, e.g. 1500×1000.',save:'SAVE TEMPLATE',default:'DEFAULT',setDefault:'SET DEFAULT',remove:'DELETE',inbox:'INBOX',outbox:'OUTBOX',emptyInbox:'No electronic QSL received yet.',emptyOutbox:'No electronic QSL sent yet.',received:'MARK RECEIVED',receivedDone:'RECEIVED',from:'FROM',to:'TO',date:'DATE',time:'TIME',freq:'FREQ',mode:'MODE',rst:'RST',uploadOk:'QSL template uploaded.',receivedOk:'QSL marked as received.'},
 ja:{kicker:'// ELECTRONIC QSL',title:'QSLセンター',intro:'自作QSL画像を背景としてアップロードできます。QSO情報は原画像に焼き込まず、送信・表示時に動的に重ねます。',templates:'QSLテンプレート',upload:'QSLをアップロード',name:'テンプレート名',pick:'画像を選択',hint:'PNG / JPEG / WebP、最大5 MB。推奨比率3:2（例 1500×1000）。',save:'テンプレート保存',default:'既定',setDefault:'既定に設定',remove:'削除',inbox:'受信箱',outbox:'送信済み',emptyInbox:'受信した電子QSLはまだありません。',emptyOutbox:'送信した電子QSLはまだありません。',received:'受信確認',receivedDone:'受信済み',from:'FROM',to:'TO',date:'DATE',time:'TIME',freq:'FREQ',mode:'MODE',rst:'RST',uploadOk:'QSLテンプレートを保存しました。',receivedOk:'QSLの受信を確認しました。'}
}[locale.value]))

async function load(){error.value='';try{const [t,i,o]=await Promise.all([api.qslTemplates(),api.qslInbox(),api.qslOutbox()]);templates.value=t.templates;inbox.value=i.messages;outbox.value=o.messages}catch(e){error.value=e.message}}
function pickFile(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024){error.value=copy.value.hint;return}const r=new FileReader();r.onload=()=>{upload.value.dataUrl=r.result;upload.value.preview=r.result;upload.value.fileName=file.name;if(!upload.value.name)upload.value.name=file.name.replace(/\.[^.]+$/,'').slice(0,80)};r.onerror=()=>error.value='File read failed.';r.readAsDataURL(file)}
async function saveTemplate(){if(!upload.value.dataUrl)return;busy.value='upload';error.value='';notice.value='';try{const r=await api.uploadQslTemplate({name:upload.value.name,dataUrl:upload.value.dataUrl,isDefault:templates.value.length===0});templates.value.unshift(r.template);if(r.template.isDefault)templates.value.forEach(x=>x.isDefault=x.id===r.template.id);upload.value={name:'',dataUrl:'',preview:'',fileName:''};notice.value=copy.value.uploadOk}catch(e){error.value=e.message}finally{busy.value=''}}
async function setDefault(item){busy.value=`def${item.id}`;try{await api.setDefaultQsl(item.id);templates.value.forEach(x=>x.isDefault=x.id===item.id)}catch(e){error.value=e.message}finally{busy.value=''}}
async function remove(item){if(!confirm(`${copy.value.remove}: ${item.name}?`))return;busy.value=`del${item.id}`;try{await api.deleteQslTemplate(item.id);templates.value=templates.value.filter(x=>x.id!==item.id);if(templates.value.length&&!templates.value.some(x=>x.isDefault))templates.value[0].isDefault=true}catch(e){error.value=e.message}finally{busy.value=''}}
async function markReceived(item){busy.value=`recv${item.id}`;try{const r=await api.markQslReceived(item.id);Object.assign(item,r.message);notice.value=copy.value.receivedOk}catch(e){error.value=e.message}finally{busy.value=''}}
function snapshot(item){return item.snapshot||{}}
onMounted(load)
</script>

<template><div class="radio-page"><div class="container"><SiteNav/><RadioSubnav/><main class="radio-main">
<header class="radio-hero compact"><p class="auth-kicker">{{copy.kicker}}</p><h1>{{copy.title}}</h1><p>{{copy.intro}}</p></header>
<PrivacyNotice kind="radioQsl" /><p v-if="error" class="form-error">{{error}}</p><p v-if="notice" class="form-success">{{notice}}</p>
<section class="radio-section"><div class="radio-section-head"><span>QSL / TEMPLATE LIBRARY</span><h2>{{copy.templates}}</h2></div>
<div class="qsl-template-layout"><form class="qsl-upload-panel" @submit.prevent="saveTemplate"><h3>{{copy.upload}}</h3><label><span>{{copy.name}}</span><input v-model="upload.name" maxlength="80" required></label><label class="qsl-file-button"><input type="file" accept="image/png,image/jpeg,image/webp" @change="pickFile"><span>{{copy.pick}}</span><small>{{upload.fileName||copy.hint}}</small></label><div v-if="upload.preview" class="qsl-upload-preview"><img :src="upload.preview" alt="QSL preview"></div><button class="primary-action" :disabled="busy==='upload'||!upload.dataUrl" type="submit">{{copy.save}}</button></form>
<div class="qsl-template-grid"><article v-for="item in templates" :key="item.id" class="qsl-template-card"><img :src="item.imageUrl" :alt="item.name"><div><strong>{{item.name}}</strong><span v-if="item.isDefault">{{copy.default}}</span></div><div class="radio-row-actions"><button v-if="!item.isDefault" :disabled="busy===`def${item.id}`" @click="setDefault(item)">{{copy.setDefault}}</button><button :disabled="busy===`del${item.id}`" @click="remove(item)">{{copy.remove}}</button></div></article><p v-if="!templates.length" class="comment-empty">{{copy.hint}}</p></div></div></section>
<section class="radio-section"><div class="qsl-tabs"><button :class="{active:tab==='inbox'}" @click="tab='inbox'">{{copy.inbox}} · {{inbox.length}}</button><button :class="{active:tab==='outbox'}" @click="tab='outbox'">{{copy.outbox}} · {{outbox.length}}</button></div>
<div v-if="(tab==='inbox'?inbox:outbox).length" class="qsl-message-grid"><article v-for="item in (tab==='inbox'?inbox:outbox)" :key="item.id" class="qsl-message-card"><div class="qsl-card-visual"><img :src="item.imageUrl" alt="Electronic QSL"><div class="qsl-overlay"><div class="qsl-overlay-call"><span>{{copy.from}}</span><strong>{{item.senderCallsign}}</strong><span>→ {{item.receiverCallsign}}</span></div><dl><div><dt>{{copy.date}}</dt><dd>{{snapshot(item).date||'—'}}</dd></div><div><dt>{{copy.time}}</dt><dd>{{String(snapshot(item).time||'').slice(0,5)}} BJT</dd></div><div><dt>{{copy.freq}}</dt><dd>{{snapshot(item).frequencyMHz ? Number(snapshot(item).frequencyMHz).toFixed(3)+' MHz':'—'}}</dd></div><div><dt>{{copy.mode}}</dt><dd>{{snapshot(item).mode||'—'}}</dd></div><div><dt>{{copy.rst}}</dt><dd>{{snapshot(item).rstSent||'—'}}</dd></div></dl></div></div><div class="qsl-message-meta"><div><strong>{{tab==='inbox'?(item.sender?.displayName||item.senderCallsign):(item.receiver?.displayName||item.receiverCallsign)}}</strong><span>{{new Date(item.sentAt).toLocaleString()}}</span><p v-if="item.message">{{item.message}}</p></div><button v-if="tab==='inbox'&&!item.receivedAt" class="secondary-action" :disabled="busy===`recv${item.id}`" @click="markReceived(item)">{{copy.received}}</button><span v-else-if="tab==='inbox'" class="qsl-received-mark">✓ {{copy.receivedDone}}</span></div></article></div><p v-else class="comment-empty">{{tab==='inbox'?copy.emptyInbox:copy.emptyOutbox}}</p></section>
</main></div><SiteFooter/></div></template>
